import{useEffect,useState}from"react";import{Activity,BarChart3,Bell,Boxes,ClipboardList,FileBarChart,FileText,Globe,History,LayoutDashboard,ListTodo,LogOut,Lock,Map,MapPinned,MessageSquare,Navigation as NavigationIcon,Package,Palette,Route,Settings,ShieldCheck,Truck,UserRound,Users,WalletCards,Wrench,Headset,User,ChevronLeft,ChevronRight}from"lucide-react";
import{logout}from"../services/auth";
export type NavRole="admin"|"operations"|"dispatch"|"logistics"|"finance"|"documentation"|"support"|"fleet"|"hr"|"driver"|"customer";
export type NavItem={key:string;label:string;icon:any;group?:string};
const admin:NavItem[]=[
{key:"dashboard",label:"Dashboard",icon:LayoutDashboard,group:"COMMAND"},
{key:"bookings",label:"Bookings",icon:ClipboardList,group:"OPERATIONS"},{key:"shipments",label:"Shipments",icon:Package,group:"OPERATIONS"},{key:"tracking",label:"Live Tracking",icon:MapPinned,group:"OPERATIONS"},{key:"routes",label:"Routes",icon:Route,group:"OPERATIONS"},
{key:"fleet",label:"Fleet",icon:Truck,group:"FLEET"},{key:"drivers",label:"Drivers",icon:UserRound,group:"FLEET"},
{key:"staff",label:"Staff & Drivers",icon:Users,group:"PEOPLE"},{key:"support",label:"Customer Support",icon:Headset,group:"PEOPLE"},{key:"tasks",label:"Tasks",icon:ListTodo,group:"PEOPLE"},
{key:"finance",label:"Finance",icon:WalletCards,group:"FINANCE"},{key:"documents",label:"Documents",icon:FileText,group:"DOCUMENTS & COMPLIANCE"},{key:"compliance",label:"Compliance",icon:ShieldCheck,group:"DOCUMENTS & COMPLIANCE"},
{key:"notifications",label:"Notifications",icon:Bell,group:"REPORTING"},{key:"reports",label:"Reports",icon:FileBarChart,group:"REPORTING"},{key:"audit",label:"Audit Logs",icon:History,group:"REPORTING"},
{key:"website",label:"Website Management",icon:Globe,group:"WEBSITE"},{key:"fleet-gallery",label:"Fleet Gallery",icon:Truck,group:"WEBSITE"},{key:"branding",label:"Branding",icon:Palette,group:"WEBSITE"},
{key:"security",label:"Security",icon:Lock,group:"SYSTEM"},{key:"settings",label:"Settings",icon:Settings,group:"SYSTEM"}];
const staffMap:any={
operations:["dashboard","tasks","bookings","shipments","drivers","tracking","notifications","profile","security"].map(k=>({key:k,label:{dashboard:"Dashboard",tasks:"My Tasks",bookings:"Bookings",shipments:"Shipments",drivers:"Drivers",tracking:"Tracking",notifications:"Notifications",profile:"My Profile",security:"Security"}[k]!,icon:{dashboard:LayoutDashboard,tasks:ListTodo,bookings:ClipboardList,shipments:Package,drivers:UserRound,tracking:MapPinned,notifications:Bell,profile:User,security:Lock}[k]})),
dispatch:["dashboard","tasks","bookings","shipments","drivers","tracking","notifications","profile","security"].map(k=>({key:k,label:{dashboard:"Dashboard",tasks:"My Tasks",bookings:"Bookings",shipments:"Shipments",drivers:"Drivers",tracking:"Tracking",notifications:"Notifications",profile:"My Profile",security:"Security"}[k]!,icon:{dashboard:LayoutDashboard,tasks:ListTodo,bookings:ClipboardList,shipments:Package,drivers:UserRound,tracking:MapPinned,notifications:Bell,profile:User,security:Lock}[k]})),
logistics:["dashboard","tasks","shipments","routes","tracking","fleet","notifications","profile","security"].map(k=>({key:k,label:{dashboard:"Dashboard",tasks:"My Tasks",shipments:"Shipments",routes:"Routes",tracking:"Tracking",fleet:"Fleet",notifications:"Notifications",profile:"My Profile",security:"Security"}[k]!,icon:{dashboard:LayoutDashboard,tasks:ListTodo,shipments:Package,routes:Route,tracking:MapPinned,fleet:Truck,notifications:Bell,profile:User,security:Lock}[k]})),
finance:["dashboard","tasks","payments","invoices","expenses","reports","notifications","profile","security"].map(k=>({key:k,label:{dashboard:"Dashboard",tasks:"My Tasks",payments:"Payments",invoices:"Invoices",expenses:"Expenses",reports:"Reports",notifications:"Notifications",profile:"My Profile",security:"Security"}[k]!,icon:{dashboard:LayoutDashboard,tasks:ListTodo,payments:WalletCards,invoices:FileText,expenses:WalletCards,reports:BarChart3,notifications:Bell,profile:User,security:Lock}[k]})),
documentation:["dashboard","tasks","documents","compliance","shipments","notifications","profile","security"].map(k=>({key:k,label:{dashboard:"Dashboard",tasks:"My Tasks",documents:"Documents",compliance:"Compliance",shipments:"Shipments",notifications:"Notifications",profile:"My Profile",security:"Security"}[k]!,icon:{dashboard:LayoutDashboard,tasks:ListTodo,documents:FileText,compliance:ShieldCheck,shipments:Package,notifications:Bell,profile:User,security:Lock}[k]})),
fleet:["dashboard","tasks","vehicles","maintenance","documents","drivers","issues","notifications","profile","security"].map(k=>({key:k,label:{dashboard:"Dashboard",tasks:"My Tasks",vehicles:"Vehicles",maintenance:"Maintenance",documents:"Documents",drivers:"Drivers",issues:"Vehicle Issues",notifications:"Notifications",profile:"My Profile",security:"Security"}[k]!,icon:{dashboard:LayoutDashboard,tasks:ListTodo,vehicles:Truck,maintenance:Wrench,documents:FileText,drivers:UserRound,issues:Wrench,notifications:Bell,profile:User,security:Lock}[k]})),
support:["dashboard","customers","bookings","tracking","support","tasks","notifications","profile","security"].map(k=>({key:k,label:{dashboard:"Dashboard",customers:"Customers",bookings:"Bookings",tracking:"Tracking",support:"Support Tickets",tasks:"My Tasks",notifications:"Notifications",profile:"My Profile",security:"Security"}[k]!,icon:{dashboard:LayoutDashboard,customers:Users,bookings:ClipboardList,tracking:MapPinned,support:Headset,tasks:ListTodo,notifications:Bell,profile:User,security:Lock}[k]})),
hr:["dashboard","tasks","staff","documents","notifications","profile","security"].map(k=>({key:k,label:{dashboard:"Dashboard",tasks:"My Tasks",staff:"Staff Records",documents:"Documents",notifications:"Notifications",profile:"My Profile",security:"Security"}[k]!,icon:{dashboard:LayoutDashboard,tasks:ListTodo,staff:Users,documents:FileText,notifications:Bell,profile:User,security:Lock}[k]}))
};
const driver:NavItem[]=[["dashboard","Dashboard",LayoutDashboard],["assignments","My Assignments",Boxes],["vehicle","My Vehicle",Truck],["route","Route & Navigation",NavigationIcon],["tracking","Live Tracking",MapPinned],["trips","Trip Records",History],["delivery","Delivery",ClipboardList],["expenses","Fuel & Expenses",WalletCards],["issues","Vehicle Issues",Wrench],["documents","Documents",FileText],["notifications","Notifications",Bell],["profile","My Profile",User],["security","Security",Lock]].map(([key,label,icon])=>({key,label,icon}));
const customer:NavItem[]=[["overview","Overview",LayoutDashboard],["booking","My Booking",ClipboardList],["tracking","Shipment Tracking",MapPinned],["cargo","Cargo Details",Package],["route","Route",Route],["documents","Documents",FileText],["payment","Payment",WalletCards],["delivery","Delivery Status",Truck],["support","Support",Headset],["notifications","Notifications",Bell],["profile","Profile",User],["security","Security",Lock]].map(([key,label,icon])=>({key,label,icon}));
export function getNavigation(role:NavRole):NavItem[]{if(role==="admin")return admin;if(role==="driver")return driver;if(role==="customer")return customer;return staffMap[role]||staffMap.operations}
export default function Navigation({role,activeKey,onSelect,workspace,logoUrl,companyName="KIRENGA CARGO"}:{role:NavRole;activeKey:string;onSelect:(key:string)=>void;workspace:string;logoUrl?:string;companyName?:string}){const[collapsed,setCollapsed]=useState(false),[mobile,setMobile]=useState(false);const items=getNavigation(role);useEffect(()=>{const close=()=>setMobile(false);window.addEventListener("resize",close);return()=>window.removeEventListener("resize",close)},[]);useEffect(()=>{setMobile(false)},[activeKey]);return <><button className="global-nav-mobile-toggle" aria-label={mobile?"Close navigation":"Open navigation"} title={mobile?"Close navigation":"Open navigation"} onClick={()=>setMobile(v=>!v)}>{mobile?<ChevronLeft/>:<ListTodo/>}</button><aside className={"global-navigation "+(collapsed?"is-collapsed ":"")+(mobile?"is-mobile-open":"")}><div className="global-nav-brand"><span className="global-nav-mark">{logoUrl?<img src={logoUrl} alt={companyName}/>:<Truck size={21} aria-hidden="true"/>}</span>{!collapsed&&<div><b>{companyName}</b><small>{workspace}</small></div>}</div><button className="global-nav-collapse" aria-label={collapsed?"Expand navigation":"Collapse navigation"} title={collapsed?"Expand navigation":"Collapse navigation"} onClick={()=>setCollapsed(v=>!v)}>{collapsed?<ChevronRight/>:<ChevronLeft/>}</button><nav aria-label="Primary navigation">{items.map((item,i)=>{const I=item.icon,prev=items[i-1],group=item.group&&item.group!==prev?.group;return <div key={item.key}>{group&&item.group&&<div className="global-nav-group">{!collapsed&&item.group}</div>}<button className={"global-nav-item "+(activeKey===item.key?"active":"")} aria-current={activeKey===item.key?"page":undefined} aria-label={item.label} title={collapsed?item.label:undefined} onClick={()=>onSelect(item.key)}><I aria-hidden="true"/>{!collapsed&&<span>{item.label}</span>}</button></div>})}</nav><div className="global-nav-footer"><button className="global-nav-item" aria-label="Logout" title={collapsed?"Logout":undefined} onClick={()=>logout()}><LogOut aria-hidden="true"/>{!collapsed&&<span>Logout</span>}</button></div></aside>{mobile&&<button className="global-nav-backdrop" aria-label="Close navigation" onClick={()=>setMobile(false)}/>}</>}
